<application>
  <component name="ActionsCollector">
    <counts>
      <entry action="$Copy" count="73" />
      <entry action="$Delete" count="90" />
      <entry action="$Paste" count="127" />
      <entry action="$SelectAll" count="33" />
      <entry action="$Undo" count="990" />
      <entry action="About" count="2" />
      <entry action="ActivateGradleToolWindow" count="1" />
      <entry action="ActivateProjectToolWindow" count="4" />
      <entry action="ActivateStructureToolWindow" count="2" />
      <entry action="Android.AnalyzeApk" count="2" />
      <entry action="Android.BuildApk" count="12" />
      <entry action="Android.CreateResourceDirectory" count="3" />
      <entry action="Android.CreateSampleDataDirectory" count="1" />
      <entry action="Android.FixAndroidRunConfigurations" count="1" />
      <entry action="Android.GenerateSignedApk" count="179" />
      <entry action="Android.LinkExternalCppProject" count="1" />
      <entry action="Android.RunAndroidAvdManager" count="18" />
      <entry action="Android.RunAndroidSdkManager" count="13" />
      <entry action="Android.SyncProject" count="85" />
      <entry action="AndroidConnectDebuggerAction" count="5" />
      <entry action="AndroidUnusedResourceAction" count="1" />
      <entry action="ChooseRunConfiguration" count="2" />
      <entry action="CleanGradleProject" count="51" />
      <entry action="CloseAllEditors" count="3" />
      <entry action="CloseAllEditorsButActive" count="3" />
      <entry action="CommentByBlockComment" count="54" />
      <entry action="ContextHelp" count="1" />
      <entry action="Convert string literal to dollar-slashy string" count="1" />
      <entry action="CreateLibraryFromFile" count="1" />
      <entry action="Debug" count="13" />
      <entry action="DialogOkAction Enter" count="44" />
      <entry action="EditorBackSpace" count="4711" />
      <entry action="EditorChooseLookupItem" count="909" />
      <entry action="EditorChooseLookupItemReplace" count="1" />
      <entry action="EditorCodeBlockEnd" count="2" />
      <entry action="EditorCompleteStatement" count="1" />
      <entry action="EditorCopy" count="594" />
      <entry action="EditorCut" count="55" />
      <entry action="EditorDelete" count="238" />
      <entry action="EditorDeleteToWordStart" count="1" />
      <entry action="EditorDown" count="411" />
      <entry action="EditorDownWithSelection" count="2" />
      <entry action="EditorDuplicate" count="17" />
      <entry action="EditorEnter" count="736" />
      <entry action="EditorEscape" count="1" />
      <entry action="EditorIndentSelection" count="2" />
      <entry action="EditorLeft" count="204" />
      <entry action="EditorLineEnd" count="6" />
      <entry action="EditorLineStart" count="3" />
      <entry action="EditorMatchBrace" count="1" />
      <entry action="EditorPaste" count="776" />
      <entry action="EditorRight" count="349" />
      <entry action="EditorSelectWord" count="3" />
      <entry action="EditorSplitLine" count="5" />
      <entry action="EditorStartNewLine" count="2" />
      <entry action="EditorTab" count="88" />
      <entry action="EditorUp" count="97" />
      <entry action="EditorUpWithSelection" count="3" />
      <entry action="ExportSettings" count="2" />
      <entry action="ExportToHTML" count="1" />
      <entry action="ExternalSystem.OpenConfig" count="1" />
      <entry action="ExternalSystem.OpenTasksActivationManager" count="1" />
      <entry action="FileChooser.Delete" count="3" />
      <entry action="FileChooser.GotoDesktop" count="18" />
      <entry action="FileChooser.GotoHome" count="4" />
      <entry action="FileChooser.GotoProject" count="1" />
      <entry action="FileChooser.NewFolder" count="45" />
      <entry action="FileChooser.Refresh" count="1" />
      <entry action="FileChooser.ShowHiddens" count="3" />
      <entry action="Find" count="9" />
      <entry action="ForceStepInto" count="87" />
      <entry action="Generate" count="8" />
      <entry action="GoogleCloudTools.DeployToAppEngine" count="1" />
      <entry action="GotoAction" count="1" />
      <entry action="GotoBookmark1" count="279" />
      <entry action="GotoClass" count="1" />
      <entry action="GotoDeclaration" count="159" />
      <entry action="GotoNextError" count="1" />
      <entry action="HideAllWindows" count="2" />
      <entry action="HippieBackwardCompletion" count="2" />
      <entry action="HippieCompletion" count="66" />
      <entry action="ImportApkAction" count="1" />
      <entry action="ImportModule" count="1" />
      <entry action="ImportProject" count="9" />
      <entry action="ImportSettings" count="13" />
      <entry action="InvalidateCaches" count="11" />
      <entry action="Kotlin.NewFile" count="1" />
      <entry action="LoadUnloadModules" count="5" />
      <entry action="MakeGradleModule" count="2" />
      <entry action="MakeGradleProject" count="97" />
      <entry action="MakeModule" count="2" />
      <entry action="MethodDown" count="2" />
      <entry action="MethodUp" count="4" />
      <entry action="MoveLineDown" count="81" />
      <entry action="MoveLineUp" count="49" />
      <entry action="MoveStatementDown" count="15" />
      <entry action="MoveStatementUp" count="21" />
     